[package]
name = "naga_oil"
version = "0.17.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "a crate for combining and manipulating shaders using naga IR"
repository = "https://github.com/bevyengine/naga_oil/"
readme = "README.md"

[features]
default = ["test_shader", "glsl"]
# enable tests that need a graphical card
test_shader = []
glsl = ["naga/glsl-in", "naga/glsl-out"]
override_any = []
prune = []
allow_deprecated = []

[dependencies]
naga = { version = "24", features = ["wgsl-in", "wgsl-out"] }
tracing = { version = "0.1", default-features = false }
regex = { version = "1.8", default-features = false }
regex-syntax = { version = "0.8", default-features = false }
thiserror = { version = "1.0", default-features = false }
codespan-reporting = { version = "0.11", default-features = false }
data-encoding = { version = "2.3.2", default-features = false, features = [ "std" ] }
bit-set = { version = "0.8.0", default-features = false }
rustc-hash = { version = "1.1.0", default-features = false }
unicode-ident = { version = "1", default-features = false }
once_cell = { version = "1.17.0", default-features = false, features = [ "std" ] }
indexmap = { version = "2", default-features = false }

[dev-dependencies]
wgpu = { version = "24", features = ["naga-ir"] }
futures-lite = "1"
tracing-subscriber = { version = "0.3", features = ["std", "fmt"] }

[patch.crates-io]
naga = { git = "https://github.com/DouglasDwyer/wgpu", rev = "ea02da92a0a6e00823e75bceee7c945eee851996" }
